name: "Release Homebrew core formula"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  homebrew:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b #v4.1.4
        with:
          # we need to be able to get the commit for a tag
          fetch-depth: 0

      - name: Get current release info
        id: release_info
        run: |
          echo -n "tag_name=$(gh release view --json tagName --jq '.tagName')" | tee -a $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump homebrew-core formula
        uses: mislav/bump-homebrew-formula-action@b3327118b2153c82da63fd9cbf58942146ee99f0 #v3
        # skip if this looks like a pre-release tag
        if: !contains(inputs.tag_name, '-')
        with:
          formula-name: syft
          # https://github.com/Homebrew/homebrew-core/blob/master/Formula/s/syft.rb
          formula-path: Formula/s/syft.rb
          tag-name: ${{ inputs.tag_name }}
          push-to: anchore/homebrew-core
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
